default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movie_library_development

test:
  <<: *default
  database: movie_library_test

production:
  <<: *default
  database: movie_library_production
  username: movie_library
  password: <%= ENV['MOVIE_LIBRARY_DATABASE_PASSWORD'] %>
